name: Deployment
run-name: Deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "📦 Deployment has started.."
      - run: |
         npm install
         npm run deploy
        env:
          CI: true
      - run: echo "🎉 Successfully deployed!"