name: New Pull Request
run-name: New Pull Request
on: [pull_request]
jobs:
  deploy:
    steps:
      - run: echo "🤯 New pull request!"
      - run: pnpm run lint:js && pnpm run lint:css && pnpm run build && pnpm run analyze
      - run: echo "🎉 Successfully done something!"